### ISSUE TITLE
Write snapshot tests using jest for home page

### ISSUE THREAD

**Issue by hunzai** [blue-ibex-labs/ibex-dao#14]
AC.
1. Write a test to check rendering of pages using https://jestjs.io/
2. Run test using `npm run test`

**Comment by Shan-barcha** [comment]
hello sir I have written a basic test for the home page please have a look

**Comment by hunzai** [comment]
@Shan-barcha where is the test? do u have a branch or a pull request?

**Comment by Shan-barcha** [comment]
yeah, sir I just created a pull request.

**Comment by Shan-barcha** [comment]
task done!
