### ISSUE TITLE
Create a minting page

### ISSUE THREAD

**Issue by hunzai** [blue-ibex-labs/ibex-dao#15]
AC

1. create a page for minting /minting 
2. provide connect wallet button
3. provide a form with the following fields 

{
  "projctName": "Mesh Token",
  "url": "ipfs://QmRzicpReutwCkM6aotuKjErFCUD213DpwPq6ByuzMJaua",
  "description": "",
  "twitter": "",
  "discord": "",
  "policyId": ""
}

**Comment by al3sha9** [comment]
![screencapture-localhost-3000-market-2023-02-02-01_51_18](https://user-images.githubusercontent.com/65455151/216160526-69468c3c-98df-4005-b9d8-0dbd3fe9966f.png)

**Comment by al3sha9** [comment]
created the form part and added some additional elements.
[Images used are dummy NFTs]

**Comment by al3sha9** [comment]
![screencapture-localhost-3000-market-2023-02-02-01_55_52](https://user-images.githubusercontent.com/65455151/216161524-e7e07191-f5ff-4506-8800-51c848a3e510.png)

**Comment by hunzai** [comment]
The form is good enough. 
We don't need to display NFTs remove that part. We will have a page for /nft - to display nfts from the wallet in this issue it is not required.

**Comment by hunzai** [comment]
Write tests for the form

**Comment by al3sha9** [comment]
**Stuck in this error and working on fixing it**
 Test suite failed to run

    SyntaxError: C:\Users\DELL\Desktop\ibex-dao\node_modules\psl\data\rules.json: Unexpected end of JSON input
        at parse (<anonymous>)

      at Object.<anonymous> (node_modules/psl/index.js:14:19)

**Comment by hunzai** [comment]
@al3sha9 where is the code? how I know when/where it fails? Can u create at least a branch?

**Comment by al3sha9** [comment]
code is in the minting-page branch sir I wrote a test for the form inputs but it was not working so i removed it and wrote a basic toBeInTheDocument test but still not working.

**Comment by hunzai** [comment]
Always link the code  in the issue. 
1. The error means your json is wrong. Use a format checker e.g. https://jsonformatter.org/ to check if json is correct

```
SyntaxError: C:\Users\DELL\Desktop\ibex-dao\node_modules\psl\data\rules.json: Unexpected end of JSON input
    at parse (<anonymous>)

  at Object.<anonymous> (node_modules/psl/index.js:14:19)
```

**Comment by hunzai** [comment]
Also merge current main branch that Shan created & use same approach to write tests

**Comment by al3sha9** [comment]
Sir i checked the json file already the file was adding an extra line at the end of the json file automatically when i saved it
