### ISSUE TITLE
Bug: NFTs list is under the header

### ISSUE THREAD

**Issue by hunzai** [blue-ibex-labs/ibex-dao#23]
Make sure the header is always static and content has a top spacing

![image](https://user-images.githubusercontent.com/208305/217908116-2ba5c178-dcc8-42e9-98c5-b06d3ab7b84b.png)

**Comment by Shan-barcha** [comment]
sure sir i am on it .

**Comment by Shan-barcha** [comment]
Sir, wouldn't it be better if we wrapped the navbar in a layout? The issue is that when I apply styling to the wallet component, other pages are also affected.

**Comment by Shan-barcha** [comment]
issue solved sir please have a look i will create a PR.

**Comment by hunzai** [comment]
@Shan-barcha yes change the navbar as well. Make all pages responsive

**Comment by Shan-barcha** [comment]
Fixed responsiveness sir please have a look !
