### ISSUE TITLE
Add NFT form to minting page

### ISSUE THREAD

**Issue by hunzai** [blue-ibex-labs/ibex-dao#27]
Add existing NFT form to page e.g. https://ibex-dao.vercel.app/minting. 

Conditions
1. If user wallet is connected then he can see form with mint information
2. If wallet is not connect the form is not visible
3. When user clicks on mint button then pass all form fields to `createTransaction` method

```
      const { assetName, maskedTx, originalMetadata } = await createTransaction(
        recipientAddress,
        utxos
      );
```
4. Use the passed information in `ibex-dao/pages/api/create-minting-transaction.ts`
```
 const asset: Mint = {
    assetName: assetName,
    assetQuantity: "1",
    metadata: assetMetadata,
    label: "721",
    recipient: {
      address: recipientAddress,
    },
  };
```
5. Update form if needed based on above required information

**Comment by al3sha9** [comment]
sir the first 2 conditions are already there I think because in our navigation bar there is no form button there is just a mint button that connects the wallet, should i redirect the page to the form-page once the wallet is connected?

**Comment by hunzai** [comment]
1. check if wallet is connected, if not then redirect.
2. once the user is connected then he shouldn't need to reconnect in other pages. 

Findout if there is a way of storing session in browser like when user logins and then his session is stored
