### ISSUE TITLE
next-auth-implementation

### ISSUE THREAD

**Issue by al3sha9** [blue-ibex-labs/ibex-dao#30]
implementing https://next-auth.js.org/ in the project for user authentication

**Comment by al3sha9** [comment]
**Next-auth authentication added**
Currently using Google, Twitter, and Github as Sign in Methods
_(Facing Server error, due to bad requests working on solving it)_

![Screenshot (10)](https://user-images.githubusercontent.com/65455151/222891118-4278fe63-04b4-482f-88df-d95f6adbd3b9.png)

**Comment by hunzai** [comment]
@al3sha9 what is the status on this?

**Comment by al3sha9** [comment]
sir, I have resolved most of the issues in lint but 2 of the conflicts are not working out one in the package-lock.json and _app.tsx can you please have a look
I have also requested you to review the updated request.
