### ISSUE TITLE
create a library using book NFTs

### ISSUE THREAD

**Issue by hunzai** [blue-ibex-labs/ibex-dao#32]
List all the books available on a specific policyId

1. get nfts (books) from policies e7514e65f977ee4b84a8e62e7d97ea2e5c11682dfe1444d8a14e74db, 1f362a4df39f451401e44fee30f27eb39712d66aae375f539be94ed6, 9cb921b32bfe214a739ed824f3f2da4e16c535a5448253d2951cc732
2. display books in each policy in groups 
3. show total books in a given policy 
4. show floor from api @hunzai will implement this

**Comment by hunzai** [comment]
@Shan-barcha I added two apis 
1.  `/api/asset?id=<assetId>`
2. `/api/assets?policy=<policyId>`

use these apis to get nfts & get get asset by id

**Comment by Shan-barcha** [comment]
sir, I am a bit confused about the API URL, I believe that there should be a base URL for these endpoints.
how would I use these endpoints? 

/api/asset?id=<assetId>
/api/assets?policy=<policyId>

**Comment by Shan-barcha** [comment]
sir I have tried with mesh js as well, using get poilcyId but it returns me an empty array, could you please a little bit more elaborate on the above task, I couldn't find   
/api/asset?id=<assetId> and 
/api/assets?policy=<policyId> 
in API. I believe there should be an asset/assets file in the API folder.

**Comment by hunzai** [comment]
@Shan-barcha the api is implemented in the backend in project. If u check the pages/api folder those are the ones.
You have to call localhost:<port>/api/asset

**Comment by Shan-barcha** [comment]
sir whenever I call that URL it returns a 404
![Screenshot from 2023-03-13 13-05-11](https://user-images.githubusercontent.com/91740097/224646651-86360935-7d0f-4b3b-9056-e08ea2e527e2.png)
![Screenshot from 2023-03-13 13-06-19](https://user-images.githubusercontent.com/91740097/224646659-bca6ba83-4e4b-480b-ba3f-d8c3fad88bf1.png)

**Comment by hunzai** [comment]
create api accounts on https://blockfrost.io/ @Shan-barcha @al3sha9 using mainnet

**Comment by Shan-barcha** [comment]
sir this is the API  response.

![Screenshot from 2023-03-13 20-23-29](https://user-images.githubusercontent.com/91740097/224748927-0f985d49-8439-4088-bf74-f5577b20e2f2.png)

**Comment by Shan-barcha** [comment]
sir in node js we return an array to list categories and then we display items from that category on a separate page shouldn't this be the case in our scenario as well?

**Comment by Shan-barcha** [comment]
code is pushed can you please check that out ..

**Comment by Shan-barcha** [comment]
when we first call the first endpoint it returns us the URL.do I need to fetch that URL again?

**Comment by hunzai** [comment]
@Shan-barcha I don't get what you mean. Please step by step what you are sending as request and the response you are getting

**Comment by Shan-barcha** [comment]
I get that sir now I am on it.

**Comment by Shan-barcha** [comment]
sir how to convert asset id to ipfs i tried but was unable to display the images
could you please have a look
![Screenshot from 2023-03-23 17-06-59](https://user-images.githubusercontent.com/91740097/227199047-f1bb6ecd-2319-44f7-a1c6-100fd8ec34fc.png)

**Comment by hunzai** [comment]
You did this in another branch, we discussed this. see https://github.com/blue-ibex-labs/ibex-dao/pull/29/files#diff-e22256f39ac14daca0b6c7400341c609995c98d4924c8c73d0a6b64d8d7006b0R9

**Comment by Shan-barcha** [comment]
sir the metadata of APIs return null ?

**Comment by Shan-barcha** [comment]
https://www.loom.com/share/e1b062da001245e9b42bf66a7c26665a
sir, please check this loom video I want your feedback and review the code, please

**Comment by Shan-barcha** [comment]
sir as I mention in a video initially I am fetching one policyID, it gives us 100 arrays each array contains assets, and
 onchain_metadata in onchain_metadata there is an image so I am displaying that image and mapping that array.
shouldn't the website will be heavy or perform low if we fetch each image one by one 

![Screenshot from 2023-04-20 03-04-30](https://user-images.githubusercontent.com/91740097/233210065-d878ca41-290d-49cb-bda0-46e6f39b9b47.png)
I have attached a screenshot of the API response please have a look

**Comment by Shan-barcha** [comment]
and one more thing sir what should be the base URL for our API? As I deployed my code it was not visible on Vercel,vercel gave us an eternal server error, I am calling API on localhost and I tried Vrecel URL but it gave us an error. is our API live or not?
