### ISSUE TITLE
Update UI components using tools mentioned in the tutorial

### ISSUE THREAD

**Issue by hunzai** [blue-ibex-labs/ibex-dao#34]
Updated UI components using https://www.youtube.com/watch?v=0fYi8SGA20k. Use all tools mentioned in the tutorial 
DONT copy paste code

**Comment by al3sha9** [comment]
sir, I have checked the youtube video and wanted to ask if the UI team (sir Shaukat, etc.) is giving us a design to work on or if we have to get inspiration from the youtube video designs and work on the UI ourselves.

**Comment by hunzai** [comment]
@al3sha9 for now just use the video to integrate some components.

**Comment by al3sha9** [comment]
Got it.sir
