### ISSUE TITLE
As a user, I want to see current balance & list of NFTs from my wallet

### ISSUE THREAD

**Issue by hunzai** [blue-ibex-labs/ibex-dao#6]
Steps
1. Install wallet on your chrome browser e.g. Nami (https://namiwallet.io/) or https://ccvault.io/app/mainnet/welcome
2. Connect wallet using a button - @al3sha9 has implemented this
3. Use https://meshjs.dev/apis/transaction to get balance and NFTs
4. Display NFTs in a table
5. Write a test to check rendering of the table using https://jestjs.io/

**Comment by Shan-barcha** [comment]
SIR, I don't receive test ADA from the Testnets faucet why?

**Comment by al3sha9** [comment]
Yes brother i was also facing this issue

**Comment by hunzai** [comment]
search for your address using https://explorer.cardano-testnet.iohkdev.io/en.
1. check if the transaction is complete
2. check your wallet /browser wallet is configured to test net

**Comment by Shan-barcha** [comment]
yes sir we did that but I don't know why it is not working.

**Comment by hunzai** [comment]
When you run into an issue, please provide following information

Title: What is the issue
Environment: testnet, wallet address
What kind of wallet you are using?. Nami, Eternl or something else?

**Comment by hunzai** [comment]
> yes sir we did that but I don't know why it is not working.

Can you provide link to the transaction? And answer above

**Comment by Shan-barcha** [comment]
title: not receiving test ada ,
environment: Testnet,
Wallet: Namii

**Comment by hunzai** [comment]
@Shan-barcha please wallet address please. I can not debug without knowing the wallet address

**Comment by Shan-barcha** [comment]
Title : Issue No 6, point 4
sir could you please me tell me more about  NFTs where should i get NFTs from .i am bit confused ,
the link you mention is about send transaction.

**Comment by hunzai** [comment]
@Shan-barcha do you need NFT for testing?

**Comment by hunzai** [comment]
The card for each NFT should contain
Use example from https://tailwindcomponents.com/component/sopping-cart & display from NFT 
1. price (dummy price)
2. image (dummy)
3. name of collection
4. asset name

**Comment by Shan-barcha** [comment]
got it sir.

**Comment by Shan-barcha** [comment]
sir, what would be the collection name?
i don't find any collection name in Jason response

**Comment by hunzai** [comment]
for now, display policyId. Later we will call another api to get the name

**Comment by Shan-barcha** [comment]
sure sir!

**Comment by Shan-barcha** [comment]
sir wrote a basic test for the initial rendering of the page. how are we going to test interactive, could you please guide us?

**Comment by Shan-barcha** [comment]
Also, the test fails when we add a dummy image path, the code is pushed!

**Comment by hunzai** [comment]
> sir wrote a basic test for the initial rendering of the page. how are we going to test interactive, could you please guide us?

The snapshot testing is static content testing i.e. you can a copy of existing dom/html and compare it with future expected html. Therefore, every time you change or create a new page you update the snapshots, see https://jestjs.io/docs/snapshot-testing#snapshot-testing-with-jest

Let me know if you need more info

**Comment by Shan-barcha** [comment]
Title : facing an error in testing .
Error : test fail when i import image from public folder .but when i directly add image path , test pass but image is not visible on UI

**Comment by Shan-barcha** [comment]
sir i just find the solution .it work can you check please !

**Comment by Shan-barcha** [comment]
@hunzai sir please review it now !
